name: Build and Publish Electron App

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest, depending on your environment

    permissions:
      contents: write  # Allow write access to the repository contents (necessary for pushing tags)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Or your preferred Node.js version

    - name: Cache Node.js dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/my-app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci
      working-directory: ./my-app

    - name: Build the Electron app
      run: npm run make
      working-directory: ./my-app

    - name: Archive the build
      run: |
        mkdir build
        mv out/* build/
        cd build
        zip -r electron-app.zip .
      working-directory: ./my-app

    # Create and push Git tag if not exists
    - name: Check if tag exists remotely and create if needed
      run: |
        VERSION=$(jq -r .version ./my-app/package.json)  # Get version from package.json
        TAG="v$VERSION"

        # Check if the tag exists remotely using GitHub CLI
        if ! gh release view $TAG >/dev/null 2>&1; then
          echo "Tag $TAG does not exist, creating and pushing the tag."
          git tag $TAG
          git push origin $TAG
        else
          echo "Tag $TAG already exists, skipping creation."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ZIP to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: my-app/build/electron-app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
