name: Build and Publish Electron App

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest, depending on your environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Or your preferred Node.js version

    - name: Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/my-app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      working-directory: ./my-app

    - name: Build the Electron app
      run: npm run make
      working-directory: ./my-app

    - name: Archive the build
      run: |
        mkdir build
        mv out/* build/
        cd build
        zip -r electron-app.zip .
      working-directory: ./my-app

    # Create a Git tag (using the version from package.json or commit hash)
    - name: Create Git tag
      run: |
        VERSION=$(jq -r .version ./my-app/package.json)  # Get version from package.json
        TAG="v$VERSION"
        git tag $TAG
        git push origin $TAG

    - name: Upload ZIP to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: my-app/build/electron-app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
